### ISSUE TITLE
Unable to parse some python packages license

### ISSUE THREAD

**Issue by taltcher** [licensee/licensed#415]
Hi, there are several packages which I'm trying to parse their license -
For example:
`user-agents`
`googleads`

For which I receive the following output:
```yml
---
name: user-agents
version: 2.2.0
type: pip
summary: A library to identify devices (phones, tablets) and their capabilities by
  parsing browser user agent strings.
homepage: https://github.com/selwin/python-user-agents
license: none
licenses: []
notices: []
```

```yml
---
name: googleads
version: 29.0.0
type: pip
summary: Google Ads Python Client Library
homepage: https://github.com/googleads/googleads-python-lib
license: none
licenses: []
notices: []

```

For the latest versions, although I can see the licenses correctly on the repo itself - could you help me understand what is causing this?
