### ISSUE TITLE
Always raises exception if using executable built with ruby-packer

### ISSUE THREAD

**Issue by yugoPanorama** [licensee/licensed#429]
I keep running into this exception any time I try to use the executable as suggested in the documentation.

The source of the error appears to be here: https://github.com/github/licensed/blob/d84a41cb9205340b8e96661b0a34ec575cb576ed/lib/licensed/sources/bundler.rb#L58

And since the executables are always built with ruby-packer, this error will always occur?

**Context:**
We tried adding the following code to our Buildkite (CI)'s `pipeline.yml` file:

```
  - label: Run license checks
    branches: "!main"
    command:
      - "curl -sSL https://github.com/github/licensed/releases/download/3.3.1/licensed-3.3.1-linux-x64.tar.gz > licensed.tar.gz"
      - "tar -xzf licensed.tar.gz --no-same-owner"
      - "rm -f licensed.tar.gz"
      - "ls -la"
      - "./licensed cache"
      - "./licensed status"
```
