### ISSUE TITLE
Bug with pnpm in subdirectory (tries both npm and pnpm resolution?)

### ISSUE THREAD

**Issue by halostatue** [licensee/licensed#679]
I maintain a repo that has three implementations of the same specification in it and I’m exploring licensed. This can be seen at [KineticCafe/app_identity@licensed](https://github.com/KineticCafe/app_identity/tree/licensed). I don't have licensed in any gem files or anything else right at the moment, so it assumes that licensed is installed globally.

The `.licensed.yml` requires some odd configuration for `pnpm` with `name` specified. If I do not specify `name`, then `license status --sources pnpm` works perfectly.

```yaml
allowed:
  - apache-2.0
  - 0bsd
  - bsd-2-clause
  - bsd-3-clause
  - mit
  - isc

reviewed:
  mix:
    - file_system # WTFPL

apps:
  - source_path: elixir
  - source_path: ruby
  - source_path: ts
```

If I specify `name`, I get a lot of errors for `npm` and none for `pnpm` unless I modify the configuration to include `sources: { npm: false, pnpm: true }` for the `ts/` app:

```yaml
name: app_identity

allowed:
  - apache-2.0
  - 0bsd
  - bsd-2-clause
  - bsd-3-clause
  - mit
  - isc

reviewed:
  mix:
    - file_system # WTFPL

apps:
  - source_path: elixir
  - source_path: ruby
  - source_path: ts
    sources:
      npm: false
      pnpm: true
```

It appears that with both `name` and `apps`, somehow both `npm` and `pnpm` are enabled.
